tripikad/trip2

app/Http/Controllers/Auth/RegistrationController.php
resources/views/pages/auth/register.blade.php
tests/AuthTest.php

* some parts are commented out from test
* fixed eula checkbox bug

auth test - ver.1

---

app/Console/Commands/ConvertNews.php
app/Http/Controllers/FrontpageController.php
config/content.php
config/content_shortnews.php
config/menu.php
resources/lang/en/content.php
resources/lang/en/menu.php
resources/views/component/content/shortnews/frontpage.blade.php
resources/views/component/menu.blade.php
resources/views/pages/admin/unpublished.blade.php
resources/views/pages/content/buysell/index.blade.php
resources/views/pages/content/internal/index.blade.php
resources/views/pages/content/news/index.blade.php
resources/views/pages/content/shortnews/index.blade.php
resources/views/pages/image/index.blade.php
tests/BasicTest.php

Splitting short news and shortnews

---

app/Console/Commands/ConvertMessages.php
app/Http/Controllers/UserController.php
app/Http/Middleware/Role.php
app/Message.php
app/User.php
database/factories/ModelFactory.php
resources/lang/en/user.php
resources/views/pages/user/message/index.blade.php
tests/AuthTest.php
tests/MessageTest.php

Message tests

---

database/factories/ModelFactory.php
resources/lang/en/menu.php
resources/views/component/auth/menu.blade.php
resources/views/pages/auth/login.blade.php
tests/AuthTest.php

Fix authentication tests

---

resources/assets/sass/component/image.scss
resources/assets/sass/component/row.scss
resources/views/component/actions.blade.php
resources/views/component/comment/index.blade.php
resources/views/component/comment/text.blade.php
resources/views/component/content/text.blade.php
resources/views/component/image.blade.php
resources/views/component/image/background.blade.php
resources/views/component/image/circle.blade.php
resources/views/component/image/landscape.blade.php
resources/views/component/row.blade.php
resources/views/component/user/activity.blade.php
resources/views/pages/content/index.blade.php
resources/views/pages/content/photo/index.blade.php
resources/views/pages/content/photo/show.blade.php
resources/views/pages/content/show.blade.php
resources/views/pages/styleguide/index.blade.php
resources/views/pages/user/edit.blade.php
resources/views/pages/user/message/index.blade.php
resources/views/pages/user/message/with.blade.php
resources/views/pages/user/show.blade.php

Row template cleanup

---

resources/views/component/label.blade.php
resources/views/pages/styleguide/index.blade.php

Add labels

---

resources/views/component/comment/text.blade.php
resources/views/component/content/text.blade.php
resources/views/component/date/long.blade.php
resources/views/component/date/relative.blade.php
resources/views/component/date/short.blade.php
resources/views/component/user/activity.blade.php
resources/views/pages/admin/unpublished.blade.php
resources/views/pages/content/buysell/index.blade.php
resources/views/pages/content/flight/index.blade.php
resources/views/pages/content/flight/show.blade.php
resources/views/pages/content/internal/index.blade.php
resources/views/pages/user/follow/index.blade.php
resources/views/pages/user/message/index.blade.php
resources/views/pages/user/message/with.blade.php
resources/views/pages/user/show.blade.php

 Add date formatters #4

---

config/menu.php
resources/views/component/footer.blade.php
resources/views/component/menu.blade.php
resources/views/component/navbar.blade.php
resources/views/pages/styleguide/index.blade.php

cleanup menus

---

app/Comment.php
app/Content.php
app/Follow.php
app/Http/Controllers/FollowController.php
app/Http/routes.php
resources/assets/sass/component/actions.scss
resources/lang/en/content.php
resources/views/component/actions.blade.php
resources/views/component/comment/description.blade.php
resources/views/component/comment/index.blade.php
resources/views/pages/follow/index.blade.php
resources/views/pages/styleguide/index.blade.php
tests/FollowTest.php

Allow to follow content

---

app/Http/Controllers/AdminController.php
app/Http/Controllers/ContentController.php
app/Http/routes.php
app/Image.php
resources/lang/en/admin.php
resources/views/component/image/create.blade.php
resources/views/pages/admin/image/index.blade.php
tests/AdminTest.php

Based on Kaspar's work. Closes #252

Allow to add images from admin page

---

app/Console/Commands/ConvertBase.php
app/Http/Controllers/UserController.php
app/Image.php
config/imagepresets.php
tests/AdminTest.php
tests/PhotoTest.php
tests/UserTest.php

Use image presets in content convert

---

app/Console/Commands/ConvertBase.php
app/Content.php
app/Http/Controllers/UserController.php
app/Image.php
app/User.php
database/factories/ModelFactory.php
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2015_09_02_115527_create_imageables_table.php
resources/assets/svg/standalone/.gitignore
resources/assets/svg/standalone/picture_none.svg
tests/PhotoTest.php
tests/UserTest.php

Move user image handling to Image

---

resources/assets/sass/component/card.scss
resources/assets/sass/component/header2.scss
resources/assets/sass/component/header3.scss
resources/assets/sass/component/row.scss
resources/assets/sass/style/typography.scss
resources/assets/sass/variables.scss
resources/views/component/card.blade.php
resources/views/component/header2.blade.php
resources/views/component/row.blade.php
resources/views/pages/styleguide/index.blade.php

Adding h3 subheaders

---

app/Http/Controllers/StyleguideController.php
resources/assets/sass/style/typography.scss
resources/views/component/destination/subheader.blade.php
resources/views/component/icon.blade.php
resources/views/pages/styleguide/index.blade.php
tests/BasicTest.php
tests/StyleguideTest.php

* Icons are automatically added
* Component subdirectories are scanned
* StyleguideTest is added

Styleguide improvements

---

app/Http/Controllers/StyleguideController.php
resources/assets/sass/component/card.scss
resources/assets/sass/style/typography.scss
resources/assets/sass/style/utils.scss
resources/views/component/actions.blade.php
resources/views/component/ad.blade.php
resources/views/component/button.blade.php
resources/views/component/card.blade.php
resources/views/component/destination/subheader.blade.php
resources/views/component/icon.blade.php
resources/views/component/label.blade.php
resources/views/component/menu.blade.php
resources/views/component/placeholder.blade.php
resources/views/component/row.blade.php
resources/views/component/subheader.blade.php
resources/views/pages/styleguide/index.blade.php

- support for component options/modifiers
- parsing scss file headers
- headers are now in YAML format

More styleguide improvements

---

tests/ContentTest.php
tests/PhotoTest.php
tests/TravelmateTest.php

Initial content tests

---

resources/views/component/date/long.blade.php
resources/views/component/date/relative.blade.php
resources/views/component/date/short.blade.php

It's easier to remove these temporary validations and fakers from 3
known files than do it all over again after front-end development.

Date components temporary validation and faker

---

resources/views/component/date/long.blade.php
resources/views/component/date/relative.blade.php
resources/views/component/date/short.blade.php

Revert "Date components temporary validation and faker"

---

resources/assets/sass/components/_list.scss
resources/assets/sass/components/_row.scss
resources/views/component/list.blade.php
resources/views/component/row.blade.php
resources/views/pages/frontpage/index.blade.php

Working towards #358. @apani is the real author

Updated list and row components

---

.scss-lint.yml
app/Http/Controllers/StyleguideController.php
resources/assets/sass/base/_base.typography.scss
resources/views/component/about.blade.php
resources/views/component/actions.blade.php
resources/views/component/badge.blade.php
resources/views/component/button.blade.php
resources/views/component/card.blade.php
resources/views/component/date/long.blade.php
resources/views/component/date/relative.blade.php
resources/views/component/date/short.blade.php
resources/views/component/destination.blade.php
resources/views/component/destination/info.blade.php
resources/views/component/destination/subheader.blade.php
resources/views/component/footer/nav.blade.php
resources/views/component/footer/social.blade.php
resources/views/component/gallery.blade.php
resources/views/component/icon.blade.php
resources/views/component/list.blade.php
resources/views/component/map.blade.php
resources/views/component/menu.blade.php
resources/views/component/news.blade.php
resources/views/component/placeholder.blade.php
resources/views/component/profile.blade.php
resources/views/component/promo.blade.php
resources/views/component/row.blade.php
resources/views/component/subheader.blade.php
resources/views/component/tags.blade.php
resources/views/component/title.blade.php
resources/views/pages/styleguide/index.blade.php

* Both title and description are supported in component headers
* $modifiers not work and are present everywhere, including component headers
* adding typography styles to styleguide

Refreshing styleguide

---

resources/assets/sass/base/_base.scss
resources/assets/sass/components/_blog.scss
resources/assets/sass/components/_card.scss
resources/assets/sass/components/_destination.scss
resources/assets/sass/components/_destination_info.scss
resources/assets/sass/components/_footer.scss
resources/assets/sass/components/_forum-list.scss
resources/assets/sass/components/_link.scss
resources/assets/sass/components/_list.scss
resources/assets/sass/components/_masthead.scss
resources/assets/sass/components/_nav.scss
resources/assets/sass/components/_news.scss
resources/assets/sass/components/_tags.scss
resources/assets/sass/components/_title.scss

Revert "Font smoothing and weights"

---

app/Http/Controllers/FrontpageController.php
resources/lang/en/frontpage.php
resources/views/component/content/forum/list.blade.php
resources/views/component/gallery.blade.php
resources/views/component/list.blade.php
resources/views/pages/frontpage/index.blade.php

Regenerated because of git and to save my time.

Connect frontpage - issue #391

---

app/Http/Controllers/Auth/ResetController.php

Now user also can see successful callback.

Custom redirection added

---

tests/AuthTest.php

Simplified registration tests based on mikkpokk work at #416

Alternative registration tests

---

composer.json
config/app.php
config/menu.php
resources/assets/sass/components/_footer.scss
resources/assets/sass/components/_nav.scss
resources/views/component/footer/nav.blade.php
resources/views/component/footer/social.blade.php
resources/views/component/nav.blade.php

Issues #267 #250 done with that

Menu framework upgrade

---

resources/assets/js/_autoselect.js
resources/views/pages/admin/image/index.blade.php

Autoselect image id field in image admin

---

.gitignore

For all those who use PhpStorm

.idea ignore added

---

app/Exceptions/Handler.php

Model not found exception

---

app/Console/Commands/ConvertAll.php
app/Console/Commands/ConvertBase.php
app/Console/Commands/ConvertIndexAliases.php
app/Console/Kernel.php
app/Http/Controllers/RedirectController.php
app/Http/routes.php
database/migrations/2015_07_12_082735_create_aliases_table.php

Redirect leftover legacy landing pages

---

tests/TestCase.php

countElements added

---

app/Comment.php
app/Message.php
resources/views/component/comment/index.blade.php
resources/views/component/user/activity.blade.php
resources/views/pages/message/with.blade.php

body_filtered attributes for comments and messages

---

public/.htaccess

View code comments also. If possible, activate these rules in server-side config then we can remove those from htaccess.

Htaccess upgrade

---

app/Image.php

Unique file names

---

resources/lang/en/content.php
resources/views/component/travelmate/user.blade.php
resources/views/pages/content/travelmate/show.blade.php

Add "Send private message" to travelmate view

---

app/Http/Controllers/ContentController.php
app/Providers/ViewComposerServiceProvider.php
config/app.php
resources/views/component/date/select.blade.php
resources/views/component/image/form.blade.php
tests/TravelmateTest.php

Make date field easier to user

---

app/Http/Controllers/ContentController.php
config/content_blog.php
config/content_buysell.php
config/content_expat.php
config/content_flight.php
config/content_forum.php
config/content_internal.php
config/content_news.php
config/content_photo.php
config/content_shortnews.php
config/content_sponsored.php
config/content_static.php
config/content_travelmate.php

Replace "latest" variable with "orderBy"

---

app/Comment.php
app/Content.php
app/Main.php
app/Message.php

getBodyFilteredAttribute clean-up

---

app/Http/Controllers/ContentController.php
config/content_buysell.php

Expire buysell content

---

app/Http/Controllers/Auth/RegistrationController.php
app/Http/Controllers/CommentController.php
app/Http/Controllers/MessageController.php

Queue email sending

---

resources/views/layouts/main.blade.php

Add Facebook sharing tags to html head

---

app/Http/Controllers/ContentController.php
app/Http/Controllers/FrontpageController.php
app/Http/Controllers/SocialController.php
app/Main.php
config/content_buysell.php
config/content_flight.php
config/content_travelmate.php
resources/views/pages/frontpage/index.blade.php
tests/CommentTest.php
tests/TravelmateTest.php

Expire content

---

resources/assets/sass/components/_profile.scss
resources/assets/sass/components/_travelmate.scss
resources/assets/sass/components/travelmate/_travelmate-user.scss
resources/views/component/comment/index.blade.php
resources/views/component/content/forum/list.blade.php
resources/views/component/content/forum/post.blade.php
resources/views/component/header.blade.php
resources/views/component/navbar/user.blade.php
resources/views/component/profile.blade.php
resources/views/component/travelmate.blade.php
resources/views/component/travelmate/list.blade.php
resources/views/component/travelmate/user.blade.php
resources/views/component/user/activity.blade.php
resources/views/pages/content/flight/index.blade.php
resources/views/pages/content/flight/show.blade.php
resources/views/pages/content/forum/index.blade.php
resources/views/pages/content/forum/show.blade.php
resources/views/pages/content/travelmate/index.blade.php
resources/views/pages/content/travelmate/show.blade.php
resources/views/pages/destination/show.blade.php
resources/views/pages/frontpage/index.blade.php
resources/views/pages/user/show.blade.php

Added a letter option to user profile if there is no image

Profile image placeholder

---

resources/assets/sass/components/_search.scss
resources/views/component/header.blade.php
resources/views/component/header/search.blade.php

Different blade template for header search, removed header search from front page

Allar search fixes

---

app/Console/Commands/ConvertFlights.php

The error message:
```
[ErrorException]                                                             
preg_replace(): Compilation failed: range out of order in character class a  
t offset 104    
```

Fix flight convert error

---

tests/ContentTest.php
tests/PhotoTest.php

Temporarily disabling content tests

---

.javascript_ignore
gulpfile.js
package.json

This is our primitive "cache-busting" strategy until we start to use Elixir #654

Delete old CSS, JS and SVG files before generating new ones

---

app/Console/Commands/ConvertStatic.php
resources/views/pages/content/flight/index.blade.php

Adding flight error price page

---

app/Http/Middleware/LoggedCookie.php

Logged cookie fix

---

.gitignore

Ignore images directory

---

app/Http/Controllers/ContentController.php
app/Http/Controllers/ContentTraits/Forum.php
app/Http/routes.php
backup/views/pages/content/forum/edit.blade.php
config/content_buysell.php
config/content_expat.php
config/content_forum.php
config/menu.php
resources/lang/et/content.php
resources/lang/et/site.php
resources/views/component/content/forum/nav.blade.php
resources/views/component/content/forum/post.blade.php
resources/views/component/image/form.blade.php
resources/views/component/profile.blade.php
resources/views/component/tags.blade.php
resources/views/pages/content/forum/edit.blade.php
resources/views/pages/content/forum/index.blade.php
tests/PhotoTest.php

V1 Launch process - STEP 1

---

.travis.yml
app/Console/Commands/ConvertIndexAliases.php
app/Http/routes.php
composer.json
config/content.php
resources/views/component/about.blade.php
resources/views/pages/auth/reset/apply.blade.php
resources/views/pages/content/travelmate/edit.blade.php
tests/CommentTest.php
tests/ContentTest.php
tests/FeedTest.php
tests/PhotoTest.php
tests/TravelmateTest.php

V1 Launch process - STEP 5

---

app/Http/Controllers/Auth/RegistrationController.php
tests/AuthTest.php

Registration redirect fix

---

gulpfile.js

Use ```gulp v1``` task for production, makes room for ```gulp``` experimentation (Elixir etc)

Gulp v1 task

---

app/Http/Controllers/UserController.php
resources/views/component/travelmate.blade.php
resources/views/component/travelmate/user.blade.php
resources/views/pages/user/edit.blade.php

- Age
- Gender
- Color selector

Disable some profile fields

---

resources/assets/sass/layouts/_one_column.scss

Too bad to not have a proper body text wrapper but hey

Minimal styling for 1-col layouts

---

config/convert.php

converter config quickfix

---

app/Http/Controllers/AdminController.php
app/Image.php
resources/lang/et/content.php
resources/lang/et/menu.php
resources/views/pages/admin/image/index.blade.php

* A rough way to display the admin images, needs cleanup later
* Improving image attachment help texts in edit forms

Fix image admin

---

public/vendor/ckeditor/config.js
resources/views/pages/content/edit.blade.php

* Less CKeditor buttons
* No content filtering
* Bigger writing area

News editor fix

---

app/Http/Controllers/Auth/ResetController.php
resources/assets/sass/components/_form.scss
tests/AuthTest.php

- auth redirects
- forum edit form size

Small fixes

---

app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/Auth/ResetController.php
app/Http/Controllers/CommentController.php
app/Http/Controllers/ContentController.php
app/Http/Controllers/FlagController.php
app/Http/Controllers/FollowController.php
app/Http/Controllers/MessageController.php

Content, comment adding, flagging, logging in etc. Be sensible about private messages!
Also, commenting out some email sending code in CommentController, see #894

Log user activity

---

resources/assets/sass/components/_body.scss
resources/assets/sass/components/_row.scss

Fix for long links in body text

Body link fix

---

resources/assets/sass/components/forum/_forum-list-nav.scss

Removed larger margin from forum nav list items

Forum nav margin fix

---

resources/assets/sass/components/_news.scss

Changed the smaller news component layout, so it has more text space on smaller screens.

News column fix

---

backup/views/pages/content/flight/index_v1_grid.blade.php
config/content_buysell.php
config/content_expat.php
config/content_flight.php
config/content_forum.php
config/content_internal.php
resources/assets/sass/base/_base.scss
resources/assets/sass/components/_masthead.scss
resources/assets/sass/components/_pagination.scss
resources/assets/sass/components/forum/_forum-post.scss
resources/lang/et/comment.php
resources/views/component/content/forum/post.blade.php
resources/views/component/image/form.blade.php
resources/views/component/masthead.blade.php
resources/views/pages/content/flight/index.blade.php
resources/views/pages/content/flight/show.blade.php
resources/views/pages/content/forum/show.blade.php
resources/views/pages/destination/show.blade.php

Quick fixes

---

app/Http/routes.php
config/content_flight.php

15 flights and user edit allowing

---

resources/assets/js/components/gallery.js
resources/assets/sass/components/_gallery.scss
resources/views/component/gallery.blade.php
resources/views/pages/destination/show.blade.php
resources/views/pages/frontpage/index.blade.php

photomodal-username/link

---

config/menu.php
resources/lang/en/menu.php
resources/lang/et/menu.php
tests/FeedTest.php

RSS links to the footer

---

app/Http/Controllers/SearchController.php

Fred search log

---

resources/lang/en/site.php
resources/lang/et/site.php
resources/views/pages/destination/show.blade.php

destination-show-description

---

app/Main.php

large image preset while displaying inline

---

README.md
app/Console/Commands/MakeComponent.php
app/Console/Commands/MakeRegion.php
app/Console/Kernel.php
config/filesystems.php

commands:
```sh
make:component
```
and
```sh
make:region
```

Adding Cusco commands

---

.stylelintrc
README.md
app/Http/Controllers/StyleguideController.php
app/Http/Regions/Footer.php
app/Http/Regions/FooterLight.php
app/Http/routes.php
app/Utils/Component.php
elixir/postcss.js
elixir/svg.js
gulpfile.js
package.json
resources/views/v2/components/Arc/Arc.css
resources/views/v2/components/Arc/Arc.vue
resources/views/v2/components/Block/Block.blade.php
resources/views/v2/components/Block/Block.css
resources/views/v2/components/Body/Body.css
resources/views/v2/components/Button/Button.blade.php
resources/views/v2/components/Button/Button.css
resources/views/v2/components/Footer/Footer.blade.php
resources/views/v2/components/Footer/Footer.css
resources/views/v2/components/Icon/Icon.css
resources/views/v2/components/Icon/Icon.vue
resources/views/v2/components/Icon/Icon.yaml
resources/views/v2/components/Link/Link.blade.php
resources/views/v2/components/Link/Link.css
resources/views/v2/svg/icon-arrow-right.svg
resources/views/v2/utils/variables.css

* Brand ```$blue``` is now ```$cyan```, new ```$blue`` is text color
* Icon support for Button
* Block, Link components
* FooterLight region
* ```show()```method on ```component()``` helper
* Misc fixes

Introducing Cusco step 2

---

resources/views/v2/components/HeaderNavbar/HeaderNavbar.css
resources/views/v2/components/HeaderNavbarMobile/HeaderNavbarMobile.css
resources/views/v2/components/HeaderSearch/HeaderSearch.css
resources/views/v2/components/HeaderSearch/HeaderSearch.vue

for headersearch, navbar, navbarmobile

white parameters 

---

resources/views/v2/layouts/main.blade.php
resources/views/v2/loaders/promo.blade.php

Convert promo loader to vanilla JS

---

app/Http/Controllers/SearchController.php
resources/views/pages/search/show.blade.php

* Show tabs even if everything is 0
* Do not show HTML code in short_body

Search fix

---

app/Comment.php
app/Content.php
resources/views/component/flags.blade.php

Like / dislike active state

---

app/Http/Controllers/ContentController.php
app/Http/Regions/Paginator.php

Filter paginate

---

app/Console/Commands/RemoveDuplicates.php
app/Console/Kernel.php

Remove duplicate topics and destinations #823

---

app/Console/Commands/ConvertMissingContent.php
app/Console/Kernel.php
app/Http/Controllers/ContentController.php
app/Http/Controllers/UserController.php
app/Main.php
resources/views/component/comment/index.blade.php
resources/views/component/comment/text.blade.php
resources/views/component/content/text.blade.php
resources/views/component/destination/users.blade.php
resources/views/component/search/results/user.blade.php
resources/views/component/user/activity.blade.php
resources/views/component/user/link.blade.php
resources/views/pages/admin/content/index.blade.php
resources/views/pages/blogtest/show.blade.php
resources/views/pages/content/forum/show.blade.php
resources/views/pages/content/index.blade.php
resources/views/pages/content/photo/index.blade.php
resources/views/pages/content/photo/show.blade.php
resources/views/pages/content/shortnews/index.blade.php
resources/views/pages/content/show.blade.php
resources/views/pages/content/travelmate/show.blade.php
resources/views/pages/destination/show.blade.php
resources/views/pages/follow/index.blade.php
resources/views/pages/frontpage/index.blade.php
resources/views/pages/message/index.blade.php
resources/views/pages/message/with.blade.php
resources/views/pages/search/results.blade.php
resources/views/pages/user/show.blade.php

Kasp missing content fix

---

app/Http/Controllers/ContentController.php
app/Main.php

Better performance for server

---

app/Http/Regions/FrontpageHeader.php
app/Http/Regions/NavbarMobile.php
app/Utils/Component.php
resources/views/v2/components/FormSelect/FormSelect.vue
resources/views/v2/components/FormSelectMultiple/FormSelectMultiple.vue
resources/views/v2/components/FrontpageDestinationSearch/FrontpageDestinationSearch.vue
resources/views/v2/components/NavbarDesktop/NavbarDesktop.vue
resources/views/v2/components/NavbarMobile/NavbarMobile.vue

Fix Vue props encoding

---

app/Http/Controllers/V2ExperimentsController.php
resources/views/v2/components/FormSelect/FormSelect.vue
resources/views/v2/components/FormSelectMultiple/FormSelectMultiple.vue
routes/web.php

- adding a demo page for dropdown usage / testing
- cleand up obsolete variables
- added some comments, more needed in future
- tried to make more sense for variable naming

Dropdown fixes and cleanup

---

app/Http/Controllers/FeedController.php
app/Utils/BodyFormatter.php
config/site.php
resources/views/v2/components/Editor/Editor.css
resources/views/v2/components/Editor/Editor.vue
resources/views/v2/components/FlightCalendar/FlightCalendar.blade.php
resources/views/v2/components/Vimeo/Vimeo.blade.php

* Vimeo component fix
* RSS body fix
* Editor toolbar fixes
* Markdown links in flightcalendar

Assorted editor fixes

---

app/Http/Controllers/Auth/ResetController.php
app/Http/Kernel.php
app/Http/Middleware/LoggedCookie.php
app/Http/Middleware/UserActivity.php
app/User.php
database/migrations/2016_07_17_181151_add_slug_to_contents.php
database/migrations/2016_07_30_215035_add_slug_to_destinations.php
database/migrations/2017_08_12_142119_add_active_at_to_users_table.php
tests/Feature/PhotoTest.php

Add active at functionality

---

app/Http/Controllers/V2ExperimentsLayoutController.php
app/Http/Controllers/V2StatisticsController.php
app/Http/Regions/FlightCard.php
resources/views/components/DestinationBar/DestinationBar.css
resources/views/components/ExperimentalCard/ExperimentalCard.blade.php
resources/views/components/ExperimentalCard/ExperimentalCard.css
resources/views/components/ExperimentalGrid/ExperimentalGrid.blade.php
resources/views/components/ExperimentalGrid/ExperimentalGrid.css
resources/views/components/FlightCard/FlightCard.blade.php
resources/views/components/FlightCard/FlightCard.css
resources/views/components/FrontpageHeader/FrontpageHeader.css
resources/views/components/Grid/Grid.blade.php
resources/views/components/Grid/Grid.css
resources/views/components/Placeholder/Placeholder.blade.php
resources/views/components/Placeholder/Placeholder.css
resources/views/layouts/Frontpage2/Frontpage2.blade.php
resources/views/layouts/Frontpage2/Frontpage2.css
resources/views/layouts/frontpage/frontpage.blade.php
resources/views/styles/grid.css
resources/views/styles/variables.css
routes/web.php

- misc fixes, including frontpage flights
- new `Grid` component (soon to replace current `GridX` components)
- temporary `.col-x-tablet` classes for frontpage fixes
- `ExperimentalGrid` and `ExperimentalCard` components for prototyping
- Experimental layouts for grids and frontpage

New layouts step 2

---

app/Console/Kernel.php

Search command every 4 hour

---

package.json
resources/views/components/Editor/Editor.vue
resources/views/components/Flag/Flag.vue
resources/views/components/IconLoader/IconLoader.vue
resources/views/components/ImagePicker/ImagePicker.vue
resources/views/components/PhotoCard/PhotoCard.vue
resources/views/main.js
tests/Browser/EditorTest.php
yarn.lock

vue-resource to axios

---

resources/views/components/AffHotelscombined/AffHotelscombined.blade.php

Moving Hotelscombined form to an iframe
